@Matchmaker_HostAddress = http://localhost:5200/api

POST {{Matchmaker_HostAddress}}/Matchmaking/Join
Content-Type: application/json

{
    "user_id":"a_1",
    "access_token":"a0983694-050c-4230-c576-bf863afc066c"
}

###

POST {{Matchmaker_HostAddress}}/Matchmaking/Cancle
Content-Type: application/json

{
    "user_id":"a_1",
    "access_token":"a0983694-050c-4230-c576-bf863afc066c"
}

###