@GsoWebServer_HostAddress = http://localhost:5000/api

POST {{GsoWebServer_HostAddress}}/Authorize/Authentication
Content-Type: application/json

{
    "user_id":"a_1",
    "service":"Google"
}

###

POST {{GsoWebServer_HostAddress}}/User/SetNickname
Content-Type: application/json
uid: 3

{
    "new_nickname":"a_2"
}

###

###
